### PR TITLE
plugged main page to main branch with auth recently merged

### PR DESCRIPTION
**Pull request by 23nith**

### CODE REVIEW

**Comment by 23nith** [comment]
@dinndev for your review

**Comment by 23nith** [comment]
@din got it, will remove build file and add it in .gitignore. 
will also convert form into react-hook-form as well. I'll let you know when its done, thanks

**Comment by 23nith** [comment]
Done removing build from this branch and also done with converting send message form into react-hook-form.
@dinndev for your approval

**Review by dinndev — COMMENTED** [review]
lgtm.

**Review by dinndev — APPROVED** [review]

**Pull request merged**
